### ISSUE TITLE
jmeter集群压测部署方案是不是完全不对？

### ISSUE THREAD

**Issue by jiangxuhui** [zuozewei/blog-example#44]
这个是你的核心压测命令：
https://github.com/zuozewei/blog-example/blob/master/Kubernetes/k8s-jmeter-cluster/jmeter_master_configmap.yaml
```
 /jmeter/apache-jmeter-*/bin/jmeter -n -t $1 `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
```
有两个问题：
1. 缺少命令-r或者-R 指定远程slave主机
2. 即使加上去也不对，
```
getent ahostsv4 jmeter-slaves-svc 

```
这个命令获取不到slave的pod ip,因为是headless服务，改成pod的可以获取ip

是我理解有问题吗？感觉你这个完全没用哇，看起来确实高大上的

**Comment by jiangxuhui** [comment]
总算解决了，解决方法：
1.jmeter_slaves_svc.yaml 添加selector
```
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  selector:
    jmeter_mode: slave
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
```
2. 修改启动命令，添加-R参数
```
 /jmeter/apache-jmeter-*/bin/jmeter -n -t $1  -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`

```
